# Generated by Django 5.1.3 on 2024-11-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_profile_current_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='exercise',
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise/sports 1-3 days a week)'), ('moderate', 'Moderately active (moderate exercise/sports 3-5 days a week)'), ('active', 'Very active (hard exercise/sports 6-7 days a week)'), ('super_active', 'Super active (very hard exercise/physical job & exercise 2x/day)')], default='sedentary', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=25, help_text='Age in years'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=170, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeline',
            field=models.IntegerField(help_text='Timeline in weeks'),
        ),
    ]
